include: package:lint/analysis_options.yaml


analyzer:
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    
    sort_pub_dependencies: ignore
    sort_unnamed_constructors_first: ignore

  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart