name: notes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flash: ^2.0.1
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.18.0
  freezed_annotation: ^0.14.1
  get_it: ^7.2.0
  google_sign_in: ^5.0.5
  injectable: ^1.4.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: null
  freezed: ^0.14.1
  injectable_generator: ^1.4.1
  lint: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
